### ISSUE TITLE
discord-helpers/integrations/youtube

### ISSUE THREAD

**Issue by SyedOmarNoor** [mindaugaskasp/discord-music-bot#1]
when I try to run the bot it says:

module.js:550
    throw err;
    ^

Error: Cannot find module 'discord-helpers/integrations/youtube'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Student\Downloads\discord server\commands\get.js:2:17)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

Can someone help?

**Comment by mindaugaskasp** [comment]
Hi,

It seems package dependencies haven't been installed for the project. How
are you deploying/running the project? Simple npm install might help.

**Comment by mindaugaskasp** [comment]
I am closing the issue, since it has been a while and you have not replied.,
